### ISSUE TITLE
[Bug] changeSharpness function fail tests

### ISSUE THREAD

**Issue by DPende** [studio-YOLO/editpix#36]

**Comment by f-aguzzi** [comment]
I think the tests broke when we moved to a change-in-place approach for the input arrays. I'm sure they worked when I pushed the original code because we would have found out earlier otherwise, through the CI tests.

The failing tests for `changeSharpness` were caused by the original arrays being modified in place, and then resulting always equal to the edited copies. By making an actual copy of the original array through slicing, the tests now work properly.

On the other hand, the failing test for `changeHighlights` was just a typo - the `changeShadows` function was called instead of `changeHighlights` in one of the tests.
