### ISSUE TITLE
[Bug] optimize contrast functionality doesn't work

### ISSUE THREAD

**Issue by DPende** [studio-YOLO/editpix#49]

**Comment by f-aguzzi** [comment]
Are you sure this isn't due to the example images already having a fully stretched gamma (most of them do, as far as I remember)? The function passed the tests, so the algorithm works.

Maybe the name is not the best, but basically this function rescales the value of each pixel so that the lowest shadow and the highest highlight become 0 and 255 respectively. Our example pictures, being stock photos, are already optimized on this front.

**Comment by DPende** [comment]
When I run the script it usually gave me this error:

![Screenshot_20240504_213211](https://github.com/studio-YOLO/editpix/assets/29159186/231078ed-83c6-465c-a255-ac90336b2fcf)

I tried changing the input image and the error seems to have disappeared.
Probably the image used was corrupt, I don't know.
For the moment it seems to work.
